### ISSUE TITLE
neptune-user-center注册不上alibaba-sentinel

### ISSUE THREAD

**Issue by zhangxiaoxu132113** [zhangxiaoxu132113/neptune-user-center#2]
想通过nacos整合sentinel来实现sentinel规则的持久化，但是在项目启动的时候，出现以下的错误，导致我们的应用注册不上sentinel；
`java.lang.RuntimeException: convert error: convert 0 rules but there are 1 rules from datasource. RuleClass: FlowRule
	at org.springframework.cloud.alibaba.sentinel.datasource.converter.SentinelConverter.convert(SentinelConverter.java:84) ~[spring-cloud-alibaba-sentinel-datasource-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.alibaba.sentinel.datasource.converter.SentinelConverter.convert(SentinelConverter.java:37) ~[spring-cloud-alibaba-sentinel-datasource-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at com.alibaba.csp.sentinel.datasource.AbstractDataSource.loadConfig(AbstractDataSource.java:48) ~[sentinel-datasource-extension-1.7.0.jar:na]
	at com.alibaba.csp.sentinel.datasource.AbstractDataSource.loadConfig(AbstractDataSource.java:44) ~[sentinel-datasource-extension-1.7.0.jar:na]
	at org.springframework.cloud.alibaba.sentinel.custom.SentinelDataSourceHandler.logAndCheckRuleType(SentinelDataSourceHandler.java:195) [spring-cloud-alibaba-sentinel-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.alibaba.sentinel.custom.SentinelDataSourceHandler.registerBean(SentinelDataSourceHandler.java:184) [spring-cloud-alibaba-sentinel-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.alibaba.sentinel.custom.SentinelDataSourceHandler.lambda$afterSingletonsInstantiated$0(SentinelDataSourceHandler.java:72) [spring-cloud-alibaba-sentinel-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at java.util.TreeMap.forEach(TreeMap.java:1005) ~[na:1.8.0_181]
	at org.springframework.cloud.alibaba.sentinel.custom.SentinelDataSourceHandler.afterSingletonsInstantiated(SentinelDataSourceHandler.java:60) [spring-cloud-alibaba-sentinel-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1277) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1265) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at com.water.neptune.usercenter.NeptuneUserCenterApplication.main(NeptuneUserCenterApplication.java:15) ~[classes/:na]
Caused by: java.lang.IllegalArgumentException: convert 0 rules but there are 1 rules from datasource. RuleClass: FlowRule
	at org.springframework.cloud.alibaba.sentinel.datasource.converter.SentinelConverter.convert(SentinelConverter.java:80) ~[spring-cloud-alibaba-sentinel-datasource-0.2.2.RELEASE.jar:0.2.2.RELEASE]`

**Comment by zhangxiaoxu132113** [comment]
http://zpycloud.com/archives/1460
按照这个文章的做法，还是会出现这个问题

**Comment by zhangxiaoxu132113** [comment]
https://sentinelguard.io/zh-cn/docs/dashboard.html
原来官方文档也说明了这点

**3.3 触发客户端初始化**
确保客户端有访问量，Sentinel 会在客户端首次调用的时候进行初始化，开始向控制台发送心跳包。

注意：您还需要根据您的应用类型和接入方式引入对应的 适配依赖，否则即使有访问量也不能被 Sentinel 统计。
